# Generated by Django 3.0.4 on 2020-06-10 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=200)),
                ('menu_type', models.CharField(choices=[('Dinner', 'Dinner Menu')], default='Dinner', max_length=70)),
                ('menu_title', models.CharField(error_messages={'required': 'Menu Title is Required'}, max_length=200)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('colour_palette', models.CharField(choices=[('#000000 #000000 #000000', 'Formal'), ('#702323 #000000 #702323', 'Modern'), ('#8f741d #000000 #000000', 'Autumn'), ('#1f4027 #0f2113 #1f4037', 'Fultur'), ('#266682 #1d2224 #1d2224', 'Oculum'), ('#000000 #000000 #c75b5d', 'Salmon')], default='#000000 #000000 #000000', max_length=23)),
                ('title_font', models.CharField(choices=[('Dancing+Script', 'Danging Script'), ('Josefin+Sans', 'Josefin Sans'), ('Reenie+Beanie', 'Reenie Beanie'), ('Nothing+You+Could+Do', 'Nothing You Could Do'), ('Tenor+Sans', 'Tenor Sans')], default='Dancing+Script', max_length=31)),
                ('base_font', models.CharField(choices=[('Roboto', 'Roboto'), ('Lato', 'Lato'), ('Open+Sans', 'Open Sans'), ('Montserrat', 'Montserrat'), ('Source Sans Pro', 'Source Sans Pro')], default='Roboto', max_length=31)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuSection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(error_messages={'required': 'Menu section name is Required'}, max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(error_messages={'required': 'Menu section order is Required'})),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_gen.Menu')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(error_messages={'required': 'Menu item name is Required'}, max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, error_messages={'required': 'Menu item price is Required'}, max_digits=5)),
                ('order', models.PositiveIntegerField(error_messages={'required': 'Menu item order is Required'})),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_gen.MenuSection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
